version: '3.8'
services:
  maria-db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: senha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - maria-db
    links:
      - maria-db
    restart: on-failure
    volumes:
      - ./build/libs:/app/build/libs