apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    name: db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: db-local-storage-class
  resources:
    requests:
      storage: 1Gi
