name: Java

on:
  push:
  workflow_dispatch:

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build
        run: ./gradlew build -x test

      - name: Test
        run: ./gradlew test

  build_image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deploy-to-ec2' && success()
    needs: code_check
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to docker hub
        run: docker login -u danielmaria -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: |
          version=$(git rev-parse --short HEAD)
          docker build -t danielmaria/lanchonetebairro-app:$version .

      - name: Publish image to DockerHub
        run: |
          version=$(git rev-parse --short HEAD)
          docker push danielmaria/lanchonetebairro-app:$version

  deploy_ec2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deploy-to-ec2' && success()
    needs: build_image
    steps:
      - name: Pull Image from docker hub
        run: |
          version=$(git rev-parse --short HEAD)
          docker pull danielmaria/lanchonetebairro-app:$version

      - name: Delete old container
        run: docker rm -f lanchonetebairro-app-container || true

      - name: Run docker container
        run: |
          version=$(git rev-parse --short HEAD)
          docker run -d -p 8080:8080 --name lanchonetebairro-app-container danielmaria/lanchonetebairro-app:$version
