name: Java

on:
  push:
  workflow_dispatch:

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build
        run: ./gradlew build -x test

      - name: Test
        run: ./gradlew test

  build_image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deploy-to-ec2' && success()
    needs: code_check
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to docker hub
        run: sudo docker login -u danielmaria -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: sudo docker build -t danielmaria/lanchonetebairro-app:latest .

      - name: Publish image to DockerHub
        run: sudo docker push danielmaria/lanchonetebairro-app:latest



  deploy_ec2:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/deploy-to-ec2' && success()
    needs: build_image
    steps:
      -  name: Checkout
         uses: actions/checkout@v2

      - name: Pull Image from docker hub
        run: sudo docker pull danielmaria/lanchonetebairro-app:latest

      - name: Delete old container
        run: sudo docker rm -f lanchonetebairro-app-container || true

      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 -e DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD}} -e DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD}} -e MYSQL_ROOT_USERNAME=${{secrets.MYSQL_ROOT_USERNAME}} --name lanchonetebairro-app-container danielmaria/lanchonetebairro-app:latest
